### ISSUE TITLE
Can not convert table in Number(MacOs app) to markdown

### ISSUE THREAD

**Issue by Jocs** [mixmark-io/turndown-plugin-gfm#11]
Hello, turndown is an excellent tool, and I was fortunate to be able to use it in [Mark Text](https://github.com/marktext/marktext/). However, I encountered some problems in the process of use. I didn't know if it was a new requirement or a bug, so I wrote this issue.

I want to copy the table in Number software to another place and turn it into markdown. The table html in Number is probably like this:

```html
<table>
  <tbody>
    <tr>
      <td>hello</td>
      <td>world</td>
    </tr>
    <tr>
      <td>hello</td>
      <td>world</td>
    </tr>
    <tr>
      <td>hello</td>
      <td>world</td>
    </tr> 
  </tbody>
</table>
```

I look up the source code in this repo, and found that html above can not pass this function:

```javascript
function isHeadingRow (tr) {
  var parentNode = tr.parentNode
  return (
    parentNode.nodeName === 'THEAD' ||
    (
      parentNode.firstChild === tr &&
      (parentNode.nodeName === 'TABLE' || isFirstTbody(parentNode)) &&
      every.call(tr.childNodes, function (n) { return n.nodeName === 'TH' })
    )
  )
}
```

Because the first row does not has `TH` cell. So turndown does not convert it to markdown.

Is this a bug or would you want to do this? I hope turndown can support html data copied from Number.

Thanks!

**Comment by domchristie** [comment]
This is not really a bug, because tables with no heading row do not convert to markdown. https://github.com/domchristie/turndown-plugin-gfm/pull/10 is a possible solution to this issue, but there is some uncertainty as to whether this should be the default behaviour or if it should be a plugin.

**Comment by Jocs** [comment]
I think this `gfm` plugin can add a `strict mode` option, the default value is `true`, when we want to convert these non-standard table, you can set the `strict mode` to `false`, so it will not change the previous behavior . What do you think?

**Comment by x8x** [comment]
Had to check commits logs to find out why suddenly turndown stopped converting my tables without a header. Although this is good for compatibility with renderers, https://github.com/domchristie/turndown-plugin-gfm/pull/10 saved my day and it would be very nice to have it included somehow.
